alphaess:
  credentials:
    username: ${ALPHAESS_USERNAME}
    password: ${ALPHAESS_PASSWORD}
energyid:
  mock: ${ENERGYID_MOCK}
  secret-url: ${ENERGYID_SECRET_URL}
  meters:
    - alphaSn: ${ALPHAESS_SN}
      remoteId: "solarAlphaEss"
      remoteName: "solarAlphaEss"
      metric: "solarPhotovoltaicProduction"
      unit: "kWh"
      readingType: "premarkedInterval"