spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  main:
    banner-mode: off

alphaess:
  base-url: "https://www.alphaess.com/api"
  endpoints:
    authentication: "/Account/Login"
    daily-stats: "/Power/SticsByPeriod"
  credentials:
    username: "foo"
    password: "bar"
  timezone: "Europe/Brussels"

energyid:
  secret-url: "https://hooks.energyid.eu/services/WebhookIn/xxxxxxxx-xxxx-xxxx-xxxx"
  max-data-batch-size: 100
  meters:
    - converterId: "FOO_BAR"
      remoteId: "FOO_BAR"
      remoteName: "FOO_BAR"
      metric: "solarPhotovoltaicProduction"
      unit: "kWh"
      readingType: "premarkedInterval"